name: Release

on:
  release:
    types:
      - published

permissions:
  id-token: write
  contents: read

jobs:
  npm:
    name: Release on npm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2

      - uses: actions/setup-node@v4
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org

      - run: bun install --frozen-lockfile

      - run: bun run build

      - name: Publish release candidate
        if: github.event.release.prerelease
        run: npm publish --access public --tag next --provenance

      - name: Publish
        if: "!github.event.release.prerelease"
        run: npm publish --access public --provenance
